#!/usr/bin/env bash
set -euo pipefail

sudo dnf install zsh

zsh_path=$(which zsh)
current_shell=$(getent passwd "$USER" | cut -d: -f7)
if [[ "$current_shell" != "$zsh_path" ]]; then
  echo "Changing default shell to zsh..."
  sudo chsh -s "$zsh_path" "$USER"
else
  echo "Default shell is already zsh. Skipping."
fi
