#!/usr/bin/env bash

set -x

sudo dnf upgrade

sudo dnf install -y \
  zsh \
  jq \
  fzf \
  autojump-zsh \
  wget \
  parallel \
  neovim \
  tmux \
  bats

sudo dnf copr enable scottames/ghostty
sudo dnf install ghostty
