#!/usr/bin/env bash
#
# Usage: ./dev-env [--dry]
#
# Copies environment config files and directories from ./env/ into $HOME.
#
# Arguments:
#   --dry  Print what would be copied without making any changes.

set -eo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
dry="0"

# Location of environment files
DEV_ENV="env"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

copy_subdirs() {
  from=$1
  to=$2

  pushd $from >/dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd >/dev/null
}

copy_dir() {
  from=$1
  to=$2

  execute rm -rf $to
  execute cp -r $from $to
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from)

  execute rm -f $to/$name
  execute cp $from $to/$name
}

log "------------ dev-env ------------"

cd $script_dir/$DEV_ENV

# ---------------------------------------------------
# Files to copy into $HOME
# ---------------------------------------------------

echo "General directories:"
copy_subdirs .config $HOME/.config
copy_subdirs .local $HOME/.local
echo "---------------------------"

echo "Shell configuration files:"
copy_file .zshrc $HOME
copy_file .zprofile $HOME
echo "---------------------------"

echo "Tmux configuration:"
copy_file .tmux.conf $HOME
copy_file .ready-tmux $HOME
copy_dir .troot $HOME/.troot
echo "---------------------------"

echo "AWS configuration:"
copy_file .aws/config $HOME/.aws
echo "---------------------------"

echo "Hammerspoon configuration:"
copy_subdirs .hammerspoon $HOME/.hammerspoon
copy_file .hammerspoon/init.lua $HOME/.hammerspoon
echo "---------------------------"

# ---------------------------------------------------

echo "----------------------------------------"
echo "Environment setup complete"
