#!/usr/bin/env bash

# Terminal Prompt
curl -sS https://starship.rs/install.sh | sh

# Ollama for local models
curl -fsSL https://ollama.com/install.sh | sh

# Hermes Agent
if command -v hermes &>/dev/null; then
  hermes update
else
  curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash
fi

# Terminal command security
cargo install tirith
