#!/usr/bin/env bash

# Key repeat — lower interval = faster repeat
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 25
gsettings set org.gnome.desktop.peripherals.keyboard delay 200

# TODO: Caps lock key remapping
# https://github.com/QubesOS/qubes-issues/issues/5484
