#!/usr/bin/env bash

if [[ -f /etc/qubes-release ]]; then
  echo "Qubes detected, skipping package install."
  return 0 2>/dev/null || exit 0
fi

sudo dnf upgrade

sudo dnf install -y \
  zsh \
  fzf \
  autojump-zsh \
  wget \
  parallel \
  neovim \
  tmux

sudo dnf copr enable scottames/ghostty
sudo dnf install ghostty
