#!/usr/bin/env bash

if command -v brew &>/dev/null; then
  echo "Homebrew already installed. Updating..."
  brew update && brew upgrade && brew cleanup
else
  echo "Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
