#!/usr/bin/env bash

brew install rustup || brew upgrade rustup

if rustup toolchain list 2>/dev/null | grep -q "^stable"; then
	rustup update
else
	rustup toolchain install stable
fi

rustup component add rust-analyzer
