#!/usr/bin/env bash

# Python
# #######################################

curl -LsSf https://astral.sh/uv/install.sh | sh

# JavaScript
# #######################################
# Install nvm (null PROFILE prevents script from writing to shell config)
PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install 24

# Rust
# #######################################
if command -v rustup &>/dev/null; then
  echo "rustup already installed. Updating..."
  rustup update
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# shellcheck source=/dev/null
source "$HOME/.cargo/env"

if ! rustup toolchain list | grep -q "^stable"; then
  rustup toolchain install stable
fi

rustup component add rust-analyzer
cargo install cargo-edit
