#!/usr/bin/env bash
set -euo pipefail

if command -v rustup &>/dev/null; then
  echo "rustup already installed. Updating..."
  rustup update
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# shellcheck source=/dev/null
source "$HOME/.cargo/env"

if ! rustup toolchain list | grep -q "^stable"; then
  rustup toolchain install stable
fi

rustup component add rust-analyzer
cargo install cargo-edit
