#!/usr/bin/env bash

if xcode-select -p &>/dev/null && pkgutil --pkg-info=com.apple.pkg.CLTools_Executables &>/dev/null; then
  echo "Xcode Command Line Tools already installed. Skipping."
else
  echo "Installing Xcode Command Line Tools..."
  xcode-select --install
fi

if command -v brew &>/dev/null; then
  echo "Homebrew already installed. Updating..."
  brew update && brew upgrade && brew cleanup
else
  echo "Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
