#!/usr/bin/env bash

# CLI tools
# ##############

brew install jq
brew install fzf
brew install tree
brew install autojump
brew install ripgrep
brew install wget
brew install parallel
brew install cheat

# Example usage: `magick ./image.heic ./image.jpeg`
brew install imagemagick

# Development Environment
# ##########################

brew install neovim
brew install --cask ghostty
brew install tmux

# AI Agents
# ##############

brew install --cask claude-code
brew install copilot-cli

# Desktop Management
# ####################

# For automating macOS with Lua scripts
brew install hammerspoon --cask

# Languages
# ####################

brew install go
