#!/usr/bin/env bash

set -x

# Python
# #######################################
curl -LsSf https://astral.sh/uv/install.sh | sh

# JavaScript
# #######################################
# Install nvm (null PROFILE prevents script from writing to shell config)
PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install 24

brew install node
brew install go
brew install elixir
